#!/bin/bash
echo "=========================================="
echo "GitHub Repository Setup"
echo "=========================================="
echo ""
echo "Your local repository is ready with 48 files committed!"
echo ""
echo "To push to GitHub, follow these steps:"
echo ""
echo "1. Go to: https://github.com/new"
echo ""
echo "2. Repository name: aws-mac-bootstrap-bedrock-sagemaker"
echo ""
echo "3. Description: Production-ready MacBook environment for AWS Bedrock, SageMaker, and Terraform"
echo ""
echo "4. Select: Public"
echo ""
echo "5. DO NOT initialize with README, .gitignore, or license"
echo ""
echo "6. Click 'Create repository'"
echo ""
echo "7. Then run these commands:"
echo ""
echo "   cd /tmp/aws-mac-bootstrap-bedrock-sagemaker"
echo "   git remote add origin https://github.com/YOUR-USERNAME/aws-mac-bootstrap-bedrock-sagemaker.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "=========================================="
